### ISSUE TITLE
Provider "memory" not found

### ISSUE THREAD

**Issue by legobyte** [marschall/memoryfilesystem#123]
The program runs without any problem when i execute it `directly with run button in intellij Idea`.
But when i export a jar file using `artifacts` then this problem appears
`java.nio.file.ProviderNotFoundException: Provider "memory" not found`
I'm using version `2.1.0` on `Windows OS`

Using these methods: 
`MemoryFileSystemBuilder.newWindows().build()`
`MemoryFileSystemBuilder.newEmpty().build()`

**Comment by marschall** [comment]
What do you mean with

> But when i export a jar file using `artifacts`

**Comment by marschall** [comment]
Closing because so feedback. Please feel free to provide additional information and re-open the issue.
