### ISSUE TITLE
Fix MemoryFileSystemTest.readSymlinkLoop()

### ISSUE THREAD

**Issue by marschall** [marschall/memoryfilesystem#37]
`MemoryFileSystemTest#readSymlinkLoop()` is failing

**Comment by openCage** [comment]
does this mean that sym link loop detection is no longer a feature ?

You can (in 0.6.3) create a symlink look e.g. by linking to the parent.

**Comment by fge** [comment]
@openCage not sure what you mean, but you are supposed to be able to create symlinks to anything; the `symlink(2)` call doesn't care. It is the reading code which is in charge of loop detection if any.

**Comment by marschall** [comment]
@openCage you're right, I removed it from the feature list

**Comment by fge** [comment]
@marschall that's quite a loss :/ Is there a way to re-introduce it? I was of relying on it for some tests  I need to perform for assertj's Path assertions... (see https://github.com/joel-costigliola/assertj-core/pull/303)

**Comment by openCage** [comment]
testing for loops is easier during link creation. It might be ok by unix to create loops, but I can't see any positive use case for it.

**Comment by fge** [comment]
@openCage that's not the problem here; all Unix filesystems allow for it, if memoryfilesystem behaves differently that makes it not suitable as a Unix filesystem!

If you want to shoot yourself in the foot, you can, after all ;)
