### ISSUE TITLE
BasicFileAttributes are seen as not supported PosixFileAttrributes

### ISSUE THREAD

**Issue by openCage** [marschall/memoryfilesystem#46]
e.g. somepath.getFileSystem().provider.setAttribute( file, "basic:lastModifiedTime", sometime );

throws java.lang.UnsupportedOperationException: file attribute viewinterface java.nio.file.attribute.PosixFileAttributeView not supported

found in 0.6.2 
worked in 0.5.4

Note: Test ran on win 7

**Comment by marschall** [comment]
Just to be sure, you mean code like this fails?

```java
    try (FileSystem fs = FileSystems.newFileSystem(URI.create("memory:somename:///p"), Collections.<String, Object>emptyMap())) {
      Path path = fs.getPath("existing.zip");
      Files.createFile(path);
      FileTime time = FileTime.fromMillis(System.currentTimeMillis());
      Files.setAttribute(path, "basic:lastModifiedTime", time);
    }
```

**Comment by marschall** [comment]
This is a side effect of #44 I should a fix shortly.

**Comment by marschall** [comment]
I just pushed 0.6.3 with a fix to Maven Central. As usual it may take a few hours to become visible.

**Comment by openCage** [comment]
yes that fixes it
