### ISSUE TITLE
BlockInputStream.read does not return an Int in the range -1..255

### ISSUE THREAD

**Issue by oxbowlakes** [marschall/memoryfilesystem#48]
This line is wrong: https://github.com/marschall/memoryfilesystem/blob/master/src/main/java/com/github/marschall/memoryfilesystem/BlockInputStream.java#L131

If you compare to `java.io.ByteArrayInputStream` which also [reads a byte from a byte array](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/io/ByteArrayInputStream.java#144), the byte should have a `& 0xff` in order to return as an int in the specified range.

that is, the method should be:

    @Override
    public int read() throws IOException {
      byte[] data = new byte[1];
      int read = this.read(data);
      if (read == -1) {
        return read;
      } else {
        return data[0] & 0xff;
      }
    }

**Comment by marschall** [comment]
I just released version 0.6.5 that should fix the issue. It may take a few hours before it shows up in Maven Central.
