### ISSUE TITLE
Original name not updated when moving file

### ISSUE THREAD

**Issue by openCage** [marschall/memoryfilesystem#62]
if you rename a file a newDirectroyStream of the parent still shows the file under the old name.
found in 7.2, still there in 7.4

        Path file = srcFile();
        Files.move( file, file.getParent().resolve( "tgt" ) );

        try( DirectoryStream<Path> kids = Files.newDirectoryStream( file.getParent() ) ) {
            assertThat( file, not( isIn( kids ) ) ); // fails
        }

**Comment by marschall** [comment]
I'll have a look. BTW I really appreciate you beating the heck out of it.
